version: '3'
services:
  client:
    image: "xsni1/client-prod:latest"
    mem_limit: 128m
    hostname: client
  server:
    image: "xsni1/server-prod:latest"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "xsni1/worker-prod:latest"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "xsni1/nginx-prod:latest"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"